name: Build and Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.vscode'
      - '.dockerignore'
      - 'Dockerfile'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            os_tag: macos
          - os: ubuntu-latest
            os_tag: ubuntu
          - os: windows-latest
            os_tag: windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.os_tag }}
          path: release/
          retention-days: 5

      - name: Get Version Number
        id: get_version
        run: echo "::set-output name=VERSION::$(jq -r .version package.json)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}-${{ matrix.os_tag }}
          name: Release ${{ steps.get_version.outputs.VERSION }} on ${{ matrix.os_tag }}
          body: Release ${{ steps.get_version.outputs.VERSION }} for ${{ matrix.os_tag }}.
          files: |
            release/${{ steps.get_version.outputs.VERSION }}/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
